### ISSUE TITLE
[问题]: TrMenu无法在最新Spigot/Paper >=1.20.2获取头颅皮肤

### ISSUE THREAD

**Issue by Dreeam-qwq** [CoderKuo/TrMenu#13]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [x] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```

```

### 🔍 详细的描述

在 [paper-1.20.2-247](https://github.com/PaperMC/Paper/commit/acc6d012b0bb7c2e781c3506a2f598adea460ae8) 中, Paper更新了上游CraftBukkit对头颅材质获取的改动，导致TrMenu无法获取头颅皮肤, 需要TrMenu更新获取头颅皮肤的方式 -> [Heads.kt#L107](https://github.com/Dreeam-qwq/TrMenu/blob/stable/v3/plugin/src/main/kotlin/trplugins/menu/util/bukkit/Heads.kt)

CraftBukkit Commit: [f4d977e794bc39db94711cd0b66addc92b8c3a3c](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/f4d977e794bc39db94711cd0b66addc92b8c3a3c)

相关Issue:
```
https://github.com/PaperMC/Paper/issues/9875
https://github.com/PaperMC/Paper/issues/9873
```

### 🗄 服务端日志

```

```

### ⚙ 配置文件

```

```

**Comment by TheFloodDragon** [comment]
Have tried to fix in #23

**Comment by TheFloodDragon** [comment]
**See** 

+ [FxRayHughes (TrMenu)](https://github.com/FxRayHughes/TrMenu/commit/38d163df04eabfd7cfc9f80ee1ee89ee8fb16dc7)
+ [XiaoJie-150 (Taboolib)](https://github.com/TabooLib/taboolib/pull/392)

Please update taboolib version !

**Comment by TheFloodDragon** [comment]
![image](https://github.com/Dreeam-qwq/TrMenu/assets/75253383/ef8b2462-072c-47b1-9dd3-ac793dc87ccd)
加油吧！

**Comment by Ghost-chu** [comment]
同等，加油！
