### ISSUE TITLE
[Feature]: add support headdb

### ISSUE THREAD

**Issue by Zarkness2** [CoderKuo/TrMenu#40]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki and determined that this feature does not exist.

### 🔗 Is there a duplicate issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 🔍 Detailed description

add support for HeadDB plugin and add possibility to use HDB:ID, SKULLS:ID in addition to source:HDB:ID and source:SKULLS:ID

https://github.com/TheSilentPro/HeadDB/tree/master
https://www.spigotmc.org/resources/headdb.84967/

**Comment by Dreeam-qwq** [comment]
This feature already existed, you can refer to https://hhhhhy.gitbook.io/trmenu-v3/menu/icon/display/material#headdatabase
try:
```
material: 'source:HeadDatabase:myHead'
or
material: 'source:HDB:random'
```

**Comment by Zarkness2** [comment]
> This feature already existed, you can refer to https://hhhhhy.gitbook.io/trmenu-v3/menu/icon/display/material#headdatabase try:
> 
> ```
> material: 'source:HeadDatabase:myHead'
> or
> material: 'source:HDB:random'
> ```

@Dreeam-qwq sorry for replying late, but isn't that for this plugin? https://www.spigotmc.org/resources/head-database.14280/

**Comment by Zarkness2** [comment]
then in the other suggestion what I am referring to is to be able to user HDB:ID without having to put source:HDB:ID

**Comment by Zarkness2** [comment]
@Dreeam-qwq ?

**Comment by aeroidesdev** [comment]
Ok, we take your suggestion, but we can't implement HDB :..., it's for consistency

**Comment by Zarkness2** [comment]
okey, no problem
