### ISSUE TITLE
[Feature]: add support for used minimessage color format

### ISSUE THREAD

**Issue by Zarkness2** [CoderKuo/TrMenu#46]
### 📚 Have you checked the Wiki

- [X] I have checked the Wiki and determined that this feature does not exist.

### 🔗 Is there a duplicate issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 🔍 Detailed description

add support to be able to use minimessage colors at the same time as legacy colors, this was a feature that the invero was going to have but since the plugin was abandoned I think it would be a pretty good feature to add to the trmenu.

**Comment by aeroidesdev** [comment]
I'll try to make MiniMessage compatible

**Comment by aeroidesdev** [comment]
After discussion, we decided to use Taboolib Components instead of MiniMessage
