### ISSUE TITLE
[功能]: Dreeam大佬对不起

### ISSUE THREAD

**Issue by lim114514** [CoderKuo/TrMenu#53]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 🔍 详细的描述

```
1. Dreeam大佬对不起
2. Dreeam大佬对不起
3. Dreeam大佬对不起
```
😭Dreeam大佬！我错了！你别拿DcRat远控我电脑了！我电脑里面的原神Beta很重要！你别圆孔我电脑了！我错了！😭

### ⚙ 配置文件

```
dreeam: "对不起"
```

**Comment by aeroidesdev** [comment]
nb

**Comment by Dreeam-qwq** [comment]
所以这和我和trmenu有半点关系吗？
