### ISSUE TITLE
[问题]: 一个变量空指针问题

### ISSUE THREAD

**Issue by 527953120** [CoderKuo/TrMenu#58]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

purpur-1.19.4.1985

### 🔍 详细的描述

全部配置删了也有，默认就存在好像
![e354d58b45f696887d9ee61a6b67ed52](https://github.com/Dreeam-qwq/TrMenu/assets/71014798/732c50e8-a2e6-42ea-b2ff-e3218881af7c)

### 🗄 服务端日志

```

```

### ⚙ 配置文件

```

```

**Comment by Dreeam-qwq** [comment]
Please try the build of latest commit https://github.com/Dreeam-qwq/TrMenu/actions/runs/9054311273
