### ISSUE TITLE
[Bug]: 启用NBTAPI后转换的Json键名没有双引号导致物品没有被当作json解析

### ISSUE THREAD

**Issue by MSCMDD** [CoderKuo/TrMenu#69]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

启用NBTAPI后转换的Json键名没有双引号导致物品没有被当作json解析
手动补全转换后Json能被解析

复现方法：
1. 手持物品执行/trm item toJson 得到{Count:1b,id:"minecraft:campfire"}
2. 此时没装NBTAPI时使用的Json无法解析（变成空格），使用新JSON则变为minecraft:scute
3. 补全{Count:1b,id:"minecraft:campfire"}为{"Count":1b,"id":"minecraft:campfire"}后Json可以正常使用

可以理解为Json解析器问题和使用NBTAPI的Json转换问题

**Comment by MSCMDD** [comment]
直接使用新Json
![a4d960868fa2d4f3d9ed198c52b9ab77](https://github.com/Dreeam-qwq/TrMenu/assets/128666602/1a1a9984-4377-4983-9861-46d029b08a56)

![11f54d75dffd8c7ce3eb9a2ac0448073](https://github.com/Dreeam-qwq/TrMenu/assets/128666602/a5b64b16-47c0-4934-8218-b6dca53c3e8f)

![3de10f1a72115739e1a53b8372102d84](https://github.com/Dreeam-qwq/TrMenu/assets/128666602/13fd35e5-b720-41e1-a903-f774a088ef03)

使用没有Hook NBTAPI的Json

![03765f94ba6f3c570436f0bf5d3b60a5](https://github.com/Dreeam-qwq/TrMenu/assets/128666602/281bffd6-b7a4-46ca-95b7-6f4ce54f6a99)

使用补全的新Json
![fc525a1a8ec5f4924c2f6ac295aae0c7](https://github.com/Dreeam-qwq/TrMenu/assets/128666602/8cd5b0fc-0c58-4555-9feb-8f381888cfad)
![3b89d7bb44c73b905db33360a6dce0bd](https://github.com/Dreeam-qwq/TrMenu/assets/128666602/970b2ad0-6a83-4c73-ada1-2f8dd2fea6aa)

**Comment by aeroidesdev** [comment]
复现失败

在 1.20.4 Paper服务器

同时测试了没有Item NBT API 和有，显然都可以获得正常解析

**Comment by aeroidesdev** [comment]
Fix in https://github.com/Dreeam-qwq/TrMenu/commit/395d8dea6c2a84dd709ec0fed5afb583fdbcf4cf
