### ISSUE TITLE
Support 1.21+ and Paper 1.20.5+

### ISSUE THREAD

**Issue by hexiruofeng** [CoderKuo/TrMenu#71]
### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 并确定没有存在该功能.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 🔍 详细的描述

1. 如题
2. Dreeam-qwq最帅
3. 坏黑其次

**Comment by Cqmmls** [comment]
是否能支持到Minecraft 1.21版本呢

**Comment by TheFloodDragon** [comment]
Please wait for the update for 1.21 of Taboolib first.

**Comment by aeroidesdev** [comment]
等坏黑

**Comment by Arminosi** [comment]
最新1.21构建对HeadDatabase兼容有问题

**Comment by Mapacheee** [comment]
hii, will be this plugin updated to 1.21.1 if is possible?

**Comment by choneas** [comment]
_The newest Taboolib supports 1.21 now. Please update it soon._

**BUT THEY ARE STILL IN DEV SO IM FOOL**

**Comment by Dreeam-qwq** [comment]
> The newest Taboolib supports 1.21 now. Please update it soon. ♥️ @Dreeam-qwq

But they are still in dev

**Comment by Mapacheee** [comment]
> > The newest Taboolib supports 1.21 now. Please update it soon. ♥️ @Dreeam-qwq
> 
> But they are still in dev

It isn't in dev now 😔 is there possible a update to 1.21? @Dreeam-qwq 🙏

**Comment by Dreeam-qwq** [comment]
> > > The newest Taboolib supports 1.21 now. Please update it soon. ♥️ @Dreeam-qwq
> > 
> > 
> > But they are still in dev
> 
> It isn't in dev now 😔 is there possible a update to 1.21? @Dreeam-qwq 🙏

no ETA, pull request is always welcome

**Comment by hexiruofeng** [comment]
Surprised by the work done by the plugin author [Bkm016](https://github.com/TabooLib/taboolib/commits?author=Bkm016), I've rushed Bkm016(坏黑) lots of times, he's crazy about updating Taboolib 6.2.0, believing that the new version will be released soon. The latest 6.2.0DEV version seems to be ready for use.  3:

**Comment by Choneas** [comment]
~~I can't wait fot it.~~

**Comment by 601704244** [comment]
I have been waiting for support for 1.21 for a long time, and I am very dissatisfied with other menu plugins. I still like to use trmenu, which has caused me to not have the menu plugin installed on my server yet. I hope to support 1.21 as soon as possible

**Comment by HYDeath** [comment]
还是很期待有生之年能更新到最新版本

**Comment by ArubikU** [comment]
I also want but i find some issue with the dev build and mythicmobs, for a strangue reason call to a path io.lumine.mythic.xicage

**Comment by ArubikU** [comment]
> I also want but i find some issue with the dev build and mythicmobs, for a strangue reason call to a path io.lumine.mythic.xicage

Who whas never used by mythic, i search in this repo and dont seem to be caused by your code but more from taboolib

**Comment by XXJNOTFOUND** [comment]
@Dreeam-qwq 坠母加油，更新1.21.1兼容的TrMenu
XXJ和你节芬ovo

**Comment by Mapacheee** [comment]
im using trmenu in 1.21 now and it works correctly, thanks 🙏

**Comment by aeroidesdev** [comment]
latest version support 1.21
