### ISSUE TITLE
[Bug]: Trmenu libraries are not downloaded

### ISSUE THREAD

**Issue by paulreob** [CoderKuo/TrMenu#81]
### 🚀 Have you tried the latest version

- [X] I have updated TrMenu to the latest version and the same bug is reproduced.

### 📚 Have you checked the Wiki

- [X] I have checked the Wiki's related content about the problem and determined that the problem exists.

### 🔗 Is there a duplicate Issue

- [X] I have looked through the existing issue and found no duplicate content, or a more detailed description of the existing issue.

### 📰 Server details

```
  | Server OS:  Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1059-oracle aarch64)
  | Server software: Paper-196 (MC: 1.20.1)
  | TabooLib: x.x.x
  | TrMenu: TrMenu-3.3.2h
```

### 🔍 Detailed description

I don't know if it's a problem with where my machine is located (158.247.125.111) Colombia
All plugins download the libraries correctly, could it be possible that the libraries that TrMenu tries to download have a country block?

### 🗄 Server log

```
https://paste.helpch.at/ruyohaxavo.makefile
```

### ⚙ Configurations

```

```

**Comment by TheFloodDragon** [comment]
网络问题

是连接超时：http://sacredcraft.cn:8081/repository/releases/
